### ISSUE TITLE
Exception is not propagated on the stream when kafka is down

### ISSUE THREAD

**Issue by StelaLeon** [akka/reactive-kafka#170]
When Kafka is down, there's no exception being propagated to the stream. I suspect the problem is with : https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/internal/ProducerStage.scala as with an implementation of by-passing this stage and implement it with a basic apache client it works just fine. 

here is how i created my producer:     
```scala
    val kafkaSink = Flow[Producer.Message[Array[Byte], String, MyMessage]]
        .via(Producer.flow(producerSettings)) 
```
this will not record any Exception when kafka is down. 

```scala  
    def createKafkaProducerFlow(producerSettings: ProducerSettings[Array[Byte], String]): Flow[Producer.Message[Array[Byte], String, SphereMessage], Producer.Result[Array[Byte], String, SphereMessage], NotUsed] = {
    val producer = producerSettings.createKafkaProducer()

    Flow[Producer.Message[Array[Byte], String, SphereMessage]]
      .map(m => {
        val p = Promise[Producer.Result[Array[Byte], String, SphereMessage]]()

        producer.send(m.record, new Callback {
          override def onCompletion(metadata: RecordMetadata, exception: Exception): Unit = {
            if (exception == null) {
              p.success(Producer.Result(metadata.offset, m))
            } else {
              p.failure(exception)
            }
          }
        })

        p.future
      })
      .mapAsync(producerSettings.parallelism)(identity)
  }
``` 

I tried to bypass the graph stage with this piece of code and it works just fine. It might be that there's a bug in this library

**Comment by 13h3r** [comment]
Looks like this is fixed in kafka client 0.10. Check this ticket for details - https://github.com/akka/reactive-kafka/issues/163

**Comment by StelaLeon** [comment]
I am not sure I understand how those 2 issues are related. Actually I am using 0.11-M3 and I can still reproduce the issue.

**Comment by 13h3r** [comment]
@StelaLeon looks like it was a bug in 0.9.x kafka client

**Comment by 13h3r** [comment]
@StelaLeon could you provide reproducible example of the problem?

**Comment by patriknw** [comment]
The reproducer is to simply run 
`test:runMain examples.scaladsl.PlainSinkExample`
without starting the Kafka server.

**Comment by StelaLeon** [comment]
@patriknw Thanks.

**Comment by patriknw** [comment]
There is an exception after the timeout of 60 seconds (default). Unfortunately that was not seen downstreams due to blocking upstream https://github.com/akka/reactive-kafka/issues/219 and missing fail fast in mapAsync https://github.com/akka/akka/issues/21318

The latter will be fixed in Akka 2.4.10

**Comment by patriknw** [comment]
I'm closing this, but it will require Akka 2.4.10 to work smoothly.
